#! /bin/bash -l
set -euo pipefail

cd "$1"
first=d3f007b3cdcefeb8dc1efbda0b675094a9a8be97
if git merge-base --is-ancestor @ $first; then
    git checkout $first -- shell.nix tests/bench/speedcenter.exec.velcom.yaml
fi

timeout -s KILL 1h time nix-shell --run 'nix-collect-garbage; mkdir -p build/release; cd build/release; cmake ../.. && make -j8' > log # 1>&2
cd tests/bench
timeout -s KILL 1h time nix --experimental-features "nix-command flakes" shell .#temci -c nix-shell ../../shell.nix --run 'export PATH=$PWD/../../build/release/stage1/bin:$PATH && temci exec --config speedcenter.yaml --in speedcenter.exec.velcom.yaml' >> log # 1>&2
nix --experimental-features "nix-command flakes" shell .#temci -c temci report run_output.yaml --reporter codespeed2
