#! /bin/bash -l
set -euo pipefail

cd "$1"
first=c972086f4af2c98d8b815441cfb305f608f3cee9
if git merge-base --is-ancestor @ $first; then
    git checkout $first -- shell.nix tests/bench/speedcenter.exec.velcom.yaml
fi

time nix-shell --run 'mkdir build; cd build; cmake .. && make -j8' > log # 1>&2
time sudo temci-shell nix-shell --run 'export PATH=$PWD/build/stage0.5/bin:$PATH && cd tests/bench && temci exec --config speedcenter.yaml --in speedcenter.exec.velcom.yaml || true' >> log # 1>&2
nix-shell --run "cd tests/bench && temci report run_output.yaml --reporter codespeed2"
